# WindowsでR/RStudioをちゃんと使う方法 {#wsl-rstudio}

## はじめに

### 問題

R/RStudioを使っていると（特にWindowsでは）いろいろな不便があります。
例えば、

- 文字化けが起こる（世界的にはUTF-8が用いられているが、日本語のWindowsはShift-JISなどが使われているので）
- パッケージのインストールができない（OneDriveを使っているとホームディレクトリが変更されるが、アカウント名にマルチバイト文字があるとパスが読み込めないため）

ということが起こりえます。

解決策としては高知工科大学の矢内先生の[RとRStudioのインストール方法の解説](https://yukiyanai.github.io/jp/resources/)にありますが、それでもWindows固有の問題が完全に消えるわけではありません。

### Linux上のR/RStudioを使う

そこで、他の選択肢としてWindowsではなくLinuxを使うというものがあります。
さらに、Linuxを使うと言っても、

1. デュアルブートで別のマシンとして扱う
1. Windows上の仮想マシンとして扱う
1. RStudio CloudやAWSでクラウド上に立てたLinuxサーバを利用する

という可能性があります。

個人的にはデュアルブートをしていますが、いろいろと技術的にハードルが高いので、R/RStudioのためだけならば、仮想マシンで十分かと思います。

仮想マシンと言ってもさらに可能性はいくつかあり、

1. VMwareやVirtualBoxなどの仮想マシンソフト
1. Windows Subsystem for Linux (WSL) 2

を使う方法が考えられます。

現時点ではGUIで扱うのであれば前者で、CUIで扱うのであれば後者となりますが、R/RStudioのためだけならば後者で十分だと思うので、その方法を解説します。

### 概要

手順としては

1. WSL2のインストール（[参考](https://qiita.com/whim0321/items/ed76b490daaec152dc69)）
1. Rのインストール（[参考](https://cran.r-project.org/bin/linux/ubuntu/)）
1. RStudio Serverのインストール（[参考]()）

になります。

## WSL2のインストール

Windowsのバージョンが2004以降であれば（普通にアップデートしていればそのはず）、コマンドプロンプトないしPowerShellを管理者権限で開き、以下のコマンドを実行すれば、Ubuntuをインストールできます。

```{bash, eval=FALSE}
wsl --install
```

- Ubuntu以外を使いたい場合はOSを指定してください。

再起動を促されるので、再起動をするとUbuntuのインストールが始まり、終了するとアカウントを作成します。
好きなアカウント名とパスワードを入力してアカウントを作成してください。

- パスワードは表示されないようになっているので、心配しないでください。
- 以降はスタートメニューでUbuntuと入力すると実行できます。

Ubuntuが起動するとコマンドプロンプトのようなターミナルが表示されるので、以下のコマンドを実行します。

```{bash, eval=FALSE}
sudo apt update
sudo apt upgrade
```

- `sudo`というのは管理者 (super user) として実行 (do) するという、おまじないです。
- "Do you want to continue?"と聞かれたら、`y`を入力してEnterを押すとインストールが開始します。

簡単に言えば、Ubuntu内のソフトウェアのアップデートを行っています。
定期的に行うことを推奨します（RやRStudio Serverもアップデートされます）。

以降、ターミナルにいろいろとコマンドを入力して実行するわけですが、コピペが面倒なので、以下のように設定をします。
Ubuntuの左上のオレンジ色の丸いマークをクリックしてプロパティを選択します。
その中に「Ctrl + Shift + C/Vをコピー/貼り付けとして使用する」とあるので、チェックを入れます。
以降、書いてある通り上記ショートカットでコピペができるようになります（Shiftも必要な点に注意）。

## Rのインストール

次に、以下のコマンドでRをインストールします。

```{bash, eval=FALSE}
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
sudo apt install --no-install-recommends r-base
```

次のコマンドを実行してRのバージョンが確認できればインストールの成功です。

```{bash, eval=FALSE}
R --version
```

## RStusio Serverのインストール

次に以下のコマンドでRStudio Serverをインストールします。
通常はRStudioをインストールしますがWSL2ではGUIをサポートしていないので（近々、される予定）、RStudio Serverを立てて、Windows上のブラウザからアクセスするという方法を取ります。

```{bash, eval=FALSE}
wget https://rstudio.org/download/latest/stable/server/bionic/rstudio-server-latest-amd64.deb
sudo apt install gdebi
sudo gdebi rstudio-server-latest-amd64.deb
```

その後、以下のコマンドを実行するとRStudio Serverが起動します。
何も表示されて**いない**場合は成功しています。

```{bash, eval=FALSE}
sudo rstudio-server start
```

- WSL2を起動するたびに実行する必要があります。

[http://localhost:8787/](http://localhost:8787/)にブラウザからアクセスするとRStudio Serverに繋がります。
最初に作成したUbuntuのアカウントのユーザー名とパスワードを入力するとRStudio Serverを利用できます。

- 毎回、打ち込むのも面倒なのでブックマークかなにかを作っておくといいでしょう。

## RStudio Server on WSL2の注意点

おそらく、以下の処理を行えば問題なくR/Rstudioを使用できると思いますが、なにか不具合があれば教えてください。

### パッケージのインストール

いくつかのパッケージはインストールできないことがあります。
大抵の場合、Ubuntuに必要なソフトがインストールされていないことが原因です。
おそらく、以下のおまじないをUbuntuのターミナルで実行すれば、うまくいきます。

```{bash, eval=FALSE}
sudo apt install build-essential libcurl4-gnutls-dev openjdk-7-* libxml2-dev libssl-dev zlib1g-dev
```

### 警告メッセージ

`tidyverse`のインストール時や呼び出し時に以下のような警告メッセージが出てくるが、とりあえずは無視しておいて良い気がします。

```{}
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
```

### 日本語フォント

デフォルトでは日本語のフォントがないので文字化けが起こりますが、例えば以下のコードでNotoフォントをインストールするとうまくいきます。

```{bash eval=FALSE}
sudo apt intall fonts-noto-cjk
```

- [Notoフォント](https://www.google.com/get/noto/help/cjk/)とはGoogleが開発しているフォントで、CJKはその中の中日韓のフォントです。

### Windows側のファイルへのアクセス

RStudioはWindows上のLinux (WSL2) で動いていますが、WSL2からWindows側のファイルにアクセスすることはできます。

具体的には`/mnt/c`がWindowsのCドライブの（WLS2から見た）パスになっています。
この中の`Users`の中にWindowsの各ユーザーのホームディレクトリがあります（ディレクトリ名はアカウント名です）。

基本的にはパスを全て打てば良いのですが、例えばユーザー名が`xxxx`の場合、

```{r eval=FALSE}
setwd("/mnt/c/Users/xxxx")
```

とワーキングディレクトリを設定してから、RStudioの（デフォルトでは）右下の`Files`パネルの中の`More`の`Go to working directory`をクリックしてWindowsのホームディレクトリに飛んで、そこからお目当てのファイルなりRProjectなりにアクセスするのが直観的かと思います。

- このコードを記載した`.Rprofile`ファイルをLinuxのホームディレクトリ（デフォルトでRStusio Serverを起動した時に表示されている場所）に保存をすれば、R起動時に自動的にワーキングディレクトリが設定されます。
