project:
  type: book
  output-dir: docs

book:
  google-analytics: "G-LLFB8XFPX5"
  title: "R/Pythonで計量政治学入門"
  author: "土井翔平"
  date: today
  sidebar:
    title: "R/Pythonで<br>計量政治学入門"
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "導入"
      chapters:
        - quick_start.qmd
        - data_frame.qmd
    - part: "データの要約"
      chapters:
        - desc_distribution.qmd
        - desc_summary.qmd
        - desc_correlation.qmd
    - part: "データの可視化"
      chapters:
        - plot_distribution.qmd
        - plot_correlation.qmd
        - plot_line.qmd
        - plot_professional.qmd
        - plot_advanced.qmd
    # - part: "回帰分析"
    - part: "データの処理"
      chapters:
        # - data_download.qmd
        - data_import.qmd
        - data_select.qmd
        - data_create.qmd
        - data_pivot.qmd
        - data_missing_values.qmd
    # - part: "統計的因果推論"
    # - part: "機械学習"
    # - part: "地理空間データ"
    # - part: "テキストデータ"
    # - part: "ネットワークデータ"
  appendices: 
    - encoding.qmd
    - session_info.qmd

bibliography: references.bib

format:
  html:
    theme:
      - materia
      - custom.scss
    include-in-header: font.html
    mainfont: Noto Sans JP
    link-external-icon: true
    link-external-newwindow: true
    code-line-numbers: true

execute: 
  warning: false

knitr: 
  opts_chunk: 
    message: false

lang: ja
